user:
  class: '\Bormborm\Controller\MainController'
  method: 'getUser'

comment:
  class: '\Bormborm\Controller\MainController'
  method: 'getComment'

post:
  class: '\Bormborm\Controller\MainController'
  method: 'getPost'


